<a href="https://colab.research.google.com/github/laiwung/20220702-python/blob/main/20220723.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#20220723

##複習一下套件載入慣用法

 import numpy as np

 import matplotlib.pyplot as plt
 
 import pandas as pd

##NumPy
 ndarray
 
 ufunc

##ndarray
 indexing
 
 slicing

In [ ]:
import numpy as np

In [ ]:
data = np.arange(25)

In [ ]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

#檢查ndarray的屬性

In [ ]:
data.dtype

dtype('int64')

In [ ]:
data.size

25

#改變ndarray的形狀

In [ ]:
data.reshape

<function ndarray.reshape>

In [ ]:
data.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# overwrite original data
data = data.reshape(5, 5)

In [ ]:
data1 = [[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]]

In [ ]:
len(data1)

5

In [ ]:
data1[2]

[10, 11, 12, 13, 14]

In [ ]:
data1[1][2]

7

In [ ]:
data1[1][1:3]

[6, 7]

In [ ]:
data[1][1:3]

array([6, 7])

In [ ]:
data1[1:3]

[[5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [ ]:
data1[1:3][1:3]

[[10, 11, 12, 13, 14]]

In [ ]:
data[1:3][1:3]

array([[10, 11, 12, 13, 14]])

In [ ]:
data[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [ ]:
data[1, 2]

7

In [ ]:
data[1, 1:3]

array([6, 7])

In [ ]:
data[0]

array([0, 1, 2, 3, 4])

In [ ]:
data[0, :]

array([0, 1, 2, 3, 4])

In [ ]:
data[:, 4]

array([ 4,  9, 14, 19, 24])

In [ ]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
data[:, 4]=0

In [ ]:
data

array([[ 0,  1,  2,  3,  0],
       [ 5,  6,  7,  8,  0],
       [10, 11, 12, 13,  0],
       [15, 16, 17, 18,  0],
       [20, 21, 22, 23,  0]])

In [ ]:
data[[1]],[[2]]

(array([[5, 6, 7, 8, 0]]), [[2]])

In [ ]:
# Fancy Indexing
data [[1, 3]],[[2, 1]]

(array([[ 5,  6,  7,  8,  0],
        [15, 16, 17, 18,  0]]), [[2, 1]])

#MatPlotLib => Matrix Plotting Library

pyplot (scripting layer) => Functional

artist layer => OOP